apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: host.minikube.internal:5000/gent/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
